Lab_WebBanSach/Controllers/BookStoreController.cs
using Lab_WebBanSach.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Lab_WebBanSach.Controllers
{
    public class BookStoreController : Controller
    {
        dbQLBansachDataContext data = new dbQLBansachDataContext();
        // GET: BookStore
        public ActionResult Index(int? page)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            var sachMoi = LaySachMoi(18);
            return View(sachMoi.ToPagedList(pageNum,pageSize));
        }
        private List<SACH> LaySachMoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }
        public ActionResult Nhaxuatban()
        {
            var nxb = from nx in data.NHAXUATBANs select nx;
            return PartialView(nxb);
        }
        public ActionResult SPTheochude(int id, int? page)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach.ToPagedList(pageNum,pageSize));
        }
        public ActionResult SPTheoNXB(int id, int? page)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes where s.Masach == id select s;
            return View(sach.Single());
        }
    }
}

Lab_WebBanSach/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab_WebBanSach.Models;

namespace Lab_WebBanSach.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        dbQLBansachDataContext db = new dbQLBansachDataContext();
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection,KHACHHANG kh)
        {
            var hoten = collection["HoTenKH"];
            var tenDN = collection["TenDN"];
            var matKhau = collection["MatKhau"];
            var matKhauNhapLai = collection["MatKhauNhapLai"];
            var diaChi = collection["DiaChi"];
            var email = collection["Email"];
            var dienThoai = collection["DienThoai"];
            var ngaySinh = String.Format("{0:MM/dd/yyyy}", collection["NgaySinh"]);
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Vui Lòng Nhập Họ Tên Khách Hàng";
            }else if (String.IsNullOrEmpty(tenDN))
            {
                ViewData["Loi2"] = "Vui Lòng Nhập Tên Đăng Nhập";
            }
            else if (String.IsNullOrEmpty(matKhau))
            {
                ViewData["Loi3"] = "Vui Lòng Nhập Mật Khẩu";
            }
            else if (String.IsNullOrEmpty(matKhauNhapLai))
            {
                ViewData["Loi4"] = "Vui Lòng Nhập Lại Mật Khẩu";
            }
            else if (String.IsNullOrEmpty(dienThoai))
            {
                ViewData["Loi5"] = "Vui Lòng Nhập SĐT";
            }
            else if (String.IsNullOrEmpty(diaChi))
            {
                ViewData["Loi6"] = "Vui Lòng Nhập Địa Chỉ";
            }
            else if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi7"] = "Vui Lòng Nhập Email";
            }
            else
            {
                kh.HoTen = hoten;
                kh.Taikhoan = tenDN;
                kh.Matkhau = matKhau;
                kh.Email = email;
                kh.DiachiKH = diaChi;
                kh.DienthoaiKH = dienThoai;
                kh.Ngaysinh = Convert.ToDateTime(ngaySinh);
                db.KHACHHANGs.InsertOnSubmit(kh);
                db.SubmitChanges();
                return RedirectToAction("DangNhap");
            }

            return this.DangKy();
        }

        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult DangNhap(FormCollection collection)
        {
            var tenDN = collection["TenDN"];
            var matKhau = collection["MatKhau"];
            if (String.IsNullOrEmpty(tenDN))
            {
                ViewData["Loi1"] = "Bạn Phải Nhập Tên Đăng Nhập ";
            }
            else if(String.IsNullOrEmpty(matKhau))
            {
                ViewData["Loi2"] = "Bạn Phải Nhập Mật Khẩu ";
            }
            else
            {
                KHACHHANG kh = db.KHACHHANGs.SingleOrDefault(n => n.Taikhoan == tenDN && n.Matkhau == matKhau);
                if (kh != null)
                {
                    ViewBag.ThongBao = "Đăng Nhập Thành Công ";
                    Session["TaiKhoan"] = kh;
                    return RedirectToAction("Index", "BookStore");
                }
                else
                {
                    ViewBag.ThongBao = "Tên Đăng Nhập Hoặc Mật Khẩu Không Đúng";
                }
            }
            return View();
        }

        public ActionResult Logout()
        {
            Session["TaiKhoan"] = null;
            return RedirectToAction("Index", "BookStore");
        }
    }
}

Lab_WebBanSach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Lab_WebBanSach/Views/Shared/_LayoutAdmin.cshtml
@using Lab_WebBanSach.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>BookStore||VHP(Admin)</title>
    <!-- Bootstrap Core CSS -->

    <link href="/Content/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom CSS -->

    <script src="https://cdn.tiny.cloud/1/z18homl2sbt0p1e6nuvltbqqmmsd3oqed0u2rf2y66kfcypl/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({selector:'textarea'});</script>

    <link href="~/Content/mainStyle.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Admin")" style="color: white; font-weight: bold;">BookStore VHP</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav" style="width: 80%">
                    <li>
                        @Html.ActionLink("QUẢN LÝ SÁCH", "Sach", "Admin")
                    </li>
                    @if (Session["TaiKhoanAdmin"] != null)
                    {
                        Admin ad = (Admin) Session["TaiKhoanAdmin"];

                        <li class="dropdown" style="float: right;">
                            <a href="#" class="dropbtn" id="365">Xin Chào : @ad.UserAdmin</a>
                            <div class="dropdown-content">
                                <a href="@Url.Action("Logout", "Admin")">Đăng Xuất</a>
                            </div>
                        </li>
                    }
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>

        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            @RenderBody()
        </div>
    </div>
    <!-- /.container -->
    <div class="container">
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; VHP</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->
    <!-- jQuery -->
    <script src="/Scripts/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/Scripts/bootstrap.min.js"></script>
</body>
</html>

Lab_WebBanSach/Views/Shared/_LayoutUser.cshtml
@using Lab_WebBanSach.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>BookStore || VHP</title>
    <!-- Bootstrap Core CSS -->

    <link href="/Content/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom CSS -->



    <link href="~/Content/mainStyle.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/BookStore/Index/" style="color: white; font-weight: bold;">BookStore VHP</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav" style="width: 80%">
                    <li>
                        @Html.ActionLink("TRANG CHỦ", "Index", "BookStore")
                    </li>
                    <li>
                        @Html.ActionLink("ĐĂNG KÝ", "DangKy", "NguoiDung")
                    </li>
                    @if (Session["TaiKhoan"] != null)
                    {
                        KHACHHANG kh = (KHACHHANG)Session["TaiKhoan"];

                        <li class="dropdown" style="float: right;">
                            <a href="#" class="dropbtn" id="365">Xin Chào : @kh.Taikhoan</a>
                            <div class="dropdown-content">
                                <a href="@Url.Action("Logout","NguoiDung")">Đăng Xuất</a>
                                
                            </div>
                        </li>
                    }
                    else
                    {
                        <li>
                            @Html.ActionLink("ĐĂNG NHẬP", "DangNhap", "NguoiDung")
                        </li>
                    }
                    <li>
                        @Html.Action("GioHangPartial", "GioHang")
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>

        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">


        <div class="row">

            <div class="col-md-3">

                <p class="lead"> CHỦ ĐỀ SÁCH</p>

                @Html.Action("Chude", "BookStore")




                <p class="lead"> NHÀ XUẤT BẢN </p>
                @Html.Action("Nhaxuatban", "BookStore")




            </div>



            <div class="col-md-9">
                <div class="row carousel-holder">
                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>


                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" style="height: 242px;" src="/Content/images/ancient-place.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" style="height: 242px;" src="/Content/images/riverside-city.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" style="height: 242px;" src="/Content/images/kayaks.jpg" alt="">
                                </div>




                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->
    <div class="container">
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; VHP</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->
    <!-- jQuery -->
    <script src="/Scripts/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/Scripts/bootstrap.min.js"></script>
</body>
</html>