Lab_WebBanSach/Controllers/BookStoreController.cs
using Lab_WebBanSach.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Lab_WebBanSach.Controllers
{
    public class BookStoreController : Controller
    {
        dbQLBansachDataContext data = new dbQLBansachDataContext();
        // GET: BookStore
        public ActionResult Index(int? page)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            var sachMoi = LaySachMoi(18);
            return View(sachMoi.ToPagedList(pageNum,pageSize));
        }
        private List<SACH> LaySachMoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }
        public ActionResult Nhaxuatban()
        {
            var nxb = from nx in data.NHAXUATBANs select nx;
            return PartialView(nxb);
        }
        public ActionResult SPTheochude(int id, int? page)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach.ToPagedList(pageNum,pageSize));
        }
        public ActionResult SPTheoNXB(int id, int? page)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes where s.Masach == id select s;
            return View(sach.Single());
        }
    }
}

Lab_WebBanSach/Views/BookStore/Chude.cshtml
@model IEnumerable<Lab_WebBanSach.Models.CHUDE>
   
<div class="list-group">
    @foreach (var item in Model)
    {
        <a href=@Url.Action("SPTheochude","BookStore",new { id = item.MaCD}) class="list-group-item">
            @item.TenChuDe
        </a>
    }
</div>

Lab_WebBanSach/Views/BookStore/Details.cshtml
@model Lab_WebBanSach.Models.SACH
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<style>
    #DatMua a{
        clear:both;
        background-color:red;
        color:white;
        width:120px;
        display:block;
        float:right;
        text-align:center;
        padding:10px;
        text-decoration:none;
        font-weight:bold;
    }
    #DatMua a:hover{
        background-color: rgb(240, 94, 98);
        color:white;
    }
</style>
<h2>THÔNG TIN CHI TIẾT SÁCH </h2>
<div>
    <div style="width:40%;float:left;border-left:dotted 1px;border-color:azure">
        <img src="~/Hinhsanpham/@Model.Anhbia" width="100%"/>
    </div>
    <div style="float:left;padding:10px;">
        <h4 style="font-weight:bold;color:red;">Tên Sách : @Model.Tensach</h4>
        <p style="text-align:justify"><span style="font-weight:bold">Mô Tả :</span>@Html.Raw(Model.Mota)</p>
        <p style="font-weight:bold">Giá Bán:<span style="color:red;font-size:16pt;"></span>@String.Format("{0:0,0}", Model.Giaban) VNĐ</p>
    </div>
    <div id="DatMua">
        <a class="btn bg-danger" href="@Url.Action("ThemGioHang","GioHang",new { @iMaSach=@Model.Masach,@strURL = Request.Url.ToString()})">
            Đặt Mua
        </a>
    </div>
</div>

Lab_WebBanSach/Views/BookStore/Index.cshtml
@using PagedList.Mvc
@using Lab_WebBanSach.Models;
@model PagedList.IPagedList<Lab_WebBanSach.Models.SACH>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}


<div class="container-fluid">
    <h3 style="Text-align:Center; color:red">Sản Phẩm Mới</h3>
    @foreach(var sach in Model)
    {
     
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details","BookStore",new { id=sach.Masach})">
                    <img src="~/Hinhsanpham/@sach.Anhbia" style="width: 250px; height: 314px;">
                    <div class="caption">
                        <h4 class="pull-right">@String.Format("{0:0,0}", sach.Giaban) VNĐ</h4>
                        <br />
                        <p style="font-weight: bold; font-size: 16px; margin-top: 10px;">@sach.Tensach</p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                </a>
            </div>
        </div>
        
    }
</div>
<div style="margin-left: 45%;">
    
    <div class="pagination" style="margin: 0 auto; width: 100%;">
        <div>Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            Trên @Model.PageCount</div>  
        <div style="margin: 20px auto">@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))</div>
    </div>
</div>

Lab_WebBanSach/Views/BookStore/Nhaxuatban.cshtml
@model IEnumerable<Lab_WebBanSach.Models.NHAXUATBAN>

<div class="list-group">
    @foreach (var item in Model)
    {
        <a href=@Url.Action("SPTheoNXB","BookStore",new { id = item.MaNXB}) class="list-group-item">
            @item.TenNXB
        </a>
    }
</div>

Lab_WebBanSach/Views/BookStore/SPTheoNXB.cshtml
@using PagedList.Mvc
@using Lab_WebBanSach.Models;
@model PagedList.IPagedList<Lab_WebBanSach.Models.SACH>
@{
    ViewBag.Title = "SPTheoNXB";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="container-fluid">
    <h3 style="text-align:center;color:red;">SÁCH THEO NHÀ XUẤT BẢN</h3>


    @foreach (var sach in Model)
    {

        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details","BookStore",new { id=sach.Masach})">
                    <img src="~/Hinhsanpham/@sach.Anhbia" width="100" style="width: 250px; height: 314px;">
                    <div class="caption">
                        <h4 class="pull-right">@String.Format("{0:0,0}", sach.Giaban) VNĐ</h4>
                        <br />
                        <p style="font-weight: bold; font-size: 16px; margin-top: 10px;">@sach.Tensach</p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                </a>
            </div>
        </div>
    }
</div>

<div style="margin-left: 45%;">

    <div class="pagination" style="margin: 0 auto; width: 100%;">
        <div>
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            Trên @Model.PageCount
        </div>
        <div style="margin: 20px auto">@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))</div>
    </div>
</div>

Lab_WebBanSach/Views/BookStore/SPTheochude.cshtml
@using PagedList.Mvc
@using Lab_WebBanSach.Models;
@model PagedList.IPagedList<Lab_WebBanSach.Models.SACH>
@{
    ViewBag.Title = "SPTheochude";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="container-fluid">
    <h3 style="text-align:center;color:red;">SÁCH THEO CHỦ ĐỀ </h3>


    @foreach (var sach in Model)
    {

        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details","BookStore",new { id=sach.Masach})">
                    <img src="~/Hinhsanpham/@sach.Anhbia" width="100"  style="width: 250px; height: 314px;">
                    <div class="caption">
                        <h4 class="pull-right">@String.Format("{0:0,0}", sach.Giaban) VNĐ</h4>
                        <br />
                        <p style="font-weight: bold; font-size: 16px; margin-top: 10px;">@sach.Tensach</p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                </a>
            </div>
        </div>
    }
</div>
<div style="margin-left: 45%;">

    <div class="pagination" style="margin: 0 auto; width: 100%;">
        <div>
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            Trên @Model.PageCount
        </div>
        <div style="margin: 20px auto">@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))</div>
    </div>
</div>